name: 'Update Credly Badges'

on: 
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  #schedule:
    # Runs at 2am UTC
    #- cron: "0 2 * * *"

  # Enable manually running workflow from Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: brett.favro@gmail.com # optional, but default will use the same from github
